#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_confd
  
  case "$(uname -s)" in
    Darwin) url_confd="https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-darwin-amd64" ;;
    *)      url_confd="https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64" ;;
  esac

  local tmp_confd="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_confd")" EXIT
  curl -sS -L -o "$tmp_confd" "$url_confd"
  chmod 755 "$tmp_confd"
  mv -f "$tmp_confd" "$shome/bin/confd.tmp"
  mv -f "$shome/bin/confd.tmp" "$shome/bin/confd"
}

main "$@"
