#!/usr/bin/env bash

function _confd_profile {
  local shome="${_confd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  CONFD_VERSION='0.11.0'
}

_confd_profile
