#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_confd="$(confd --version | awk '{print $2}' || true)"
  jq -n --arg confd "$ver_confd" '{confd: $confd}'
}

version "$@"
